site_name: ASGI WebDAV Server
repo_url: https://github.com/rexzhang/asgi-webdav
repo_name: rexzhang/asgi-webdav
plugins:
  - search
  - git-revision-date
theme:
  name: material
  language: en
  font: false
