site_name: ASGI WebDAV Server
repo_url: https://github.com/rexzhang/asgi-webdav
repo_name: rexzhang/asgi-webdav
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - toc.integrate
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home:
    - index.md
    - compatibility.md
    - changelog.md
    - GitHub: https://github.com/rexzhang/asgi-webdav
    - Docker Hub: https://hub.docker.com/r/ray1ex/asgi-webdav
    - contributing.md
  - Getting started:
    - setup/index.md
    - setup/quick-start.md
  - Reference:
    - reference/config.md
    - reference/config-file.md
    - reference/env-value.md
    - reference/cli.md
    - reference/misc.md
  - How To:
    - ... | flat
  - Trouble Shooting:
    - known-issues.md
    - trouble-shooting.md
plugins:
  - search
  - awesome-pages
  - git-revision-date
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      languages:
        en: English
        ru: русский
        zh: 中文
      nav_translations:
        zh:
          Home: 首页
          Getting started: 开始配置
          Reference: 参考
          How To: 如何做
          Trouble Shooting: 问题处理
