# https://github.com/pre-commit/action
name: pre-commit

on:
  push:
    branches:
      - main
    paths:
      - "**.py"

  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3
